authors: [ josetan ]
name: FishingPot
main: jb.minecolab.fishingPot.Main
version: 1.2.0
api-version: 1.16

commands:
  fp:
    description: Recarga la configuración de FishingPot
    usage: /<command> reload
    permission: fishingpot.reload

permissions:
  fishingpot.reload:
    description: Permite usar el comando /fp reload para recargar la configuración
    default: op

